export const KEY_PREFIX = 'reduxPersist:'
export const REHYDRATE = 'persist/REHYDRATE'
export const ENTITY_KEYS = [
  "entities",
  "activeUploads",
  "attachments",
  "cars",
  "company",
  "dirtyEntities",
  "expenseAccounts",
  "expenseCategories",
  "expenses",
  "goals",
  "mileageHoursSetup",
  "mileages",
  "oAuthAccounts",
  "pendingExpenses",
  "pendingMileages",
  "pendingRevenues",
  "referrals",
  "revenueEntries",
  "subscription",
  "taxPayments",
  "userGoalSetup",
  "userTaxSetup",
  "vendors",
  "workItems",
  "workTypes",
];
